language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - sudo apt-get install zip
  - sudo apt-get install xorg-dev libglu1-mesa-dev
  - ./install.sh
script: ./run_tests.sh
